allow_licenses:
  - 'GPL-3.0-or-later'
  - 'GPL-3.0-only'
  - 'GPL-2.0-or-later'
  - 'LGPL-3.0-or-later'
  - 'LGPL-2.1-or-later'
  - 'Apache-2.0'
  - 'Artistic-2.0'
  - 'ClArtistic'
  - 'BSL-1.0'
  - '0BSD'
  - 'BSD-3-Clause'
  - 'CC0-1.0'
  - 'CECILL-2.0'
  - 'BSD-3-Clause-Clear'
  - 'eCos-2.0'
  - 'ECL-2.0'
  - 'EFL-2.0'
  - 'EUDatagrid'
  - 'BSD-2-Clause-FreeBSD'
  - 'FTL'
  - 'HPND'
  - 'iMatix'
  - 'Imlib2'
  - 'IJG'
  - 'Intel'
  - 'ISC'
  - 'MIT'
  - 'MPL-2.0'
  - 'NCSA'
  - 'OLDAP-2.7'
  - 'Python-2.0.1'
  - 'Ruby'
  - 'SGI-B-2.0'
  - 'SMLNJ'
  - 'Unicode-3.0'
  - 'UPL-1.0'
  - 'Unlicense'
  - 'Vim'
  - 'W3C'
  - 'WTFPL'
  - 'X11'
  - 'XFree86-1.1'
  - 'Zlib'
  - 'ZPL-2.0'
  - 'ZPL-2.1'
